### ISSUE TITLE
Re Setup

### ISSUE THREAD

**Issue by Wedgetail52** [UltraSalem/mightykingdoms#21]
Are we happy for people to use blank bases / templates to make up their 3k points? 

Snake Draft. I think we should use a snake draft for the setup. That is, players go in turn order to choose their capital, and then reverse order to place their extra adjacent tiles & armies. And to speed things up I think extra tiles and armies should be placed at once. Snake draft will stop the person who just happened to get a high order from having too much of an advantage.

If happy with these let me know and I will edit the doc.

**Comment by UltraSalem** [comment]
Sounds fine to me. 

It's pretty unlikely we'll be hitting 3000 points anyway, you'd have to be very focused on fighting a single enemy who's very focused on fighting you off. 

Snake draft should simplify setup without unbalancing things and will be easier at high player counts which I wasn't thinking of when writing the setup rules (I was just thinking 3-4).

**Comment by Wedgetail52** [comment]
ok I will update the relevant sections today sometime.
