### ISSUE TITLE
Player numbers / Game Administrator

### ISSUE THREAD

**Issue by Wedgetail52** [UltraSalem/mightykingdoms#22]
Can we get a definitive number on how many players we can fit in for setup?

Also, if we have too many people dead keen for it all, I'm happy to step back and play as the GM & flex player, that is, I will play my Orc Raiders if a player is absent that round, and just generally do bookwork.

**Comment by UltraSalem** [comment]
I'll set up a map today and see how big I can get it

**Comment by UltraSalem** [comment]
answer was 12 players, 220+ tiles, 112cm x 88cm board (roughly 3' x 4').
